### ISSUE TITLE
Unable to edit a proposition

### ISSUE THREAD

**Issue by carlgieringer** [Howdju/howdju#324]
```
RangeError: Maximum call stack size exceeded
    at t (http://localhost:3000/premiser-ui.js:68520:409)
    at A (http://localhost:3000/premiser-ui.js:68520:3097)
    at http://localhost:3000/premiser-ui.js:68520:2697
    at http://localhost:3000/premiser-ui.js:68520:917
    at Array.forEach (<anonymous>)
    at i (http://localhost:3000/premiser-ui.js:68520:873)
    at M (http://localhost:3000/premiser-ui.js:68520:2671)
    at A (http://localhost:3000/premiser-ui.js:68520:3134)
    at http://localhost:3000/premiser-ui.js:68520:2697
    at http://localhost:3000/premiser-ui.js:68520:917
```

Error appears to be in immer; install `source-map-loader` to try and get the right line numbers.

**Comment by carlgieringer** [comment]
See also #262.
