### ISSUE TITLE
Fix esbuild/jsdom/canvas API build issue

### ISSUE THREAD

**Issue by carlgieringer** [Howdju/howdju#434]
Running the API results in:

```
※ yarn run start:api:local
Building & running bin/esbuild-local-server.js
Building script bin/esbuild-local-server.js

  dist/bin/esbuild-local-server.js  13.0mb ⚠️

⚡ Done in 476ms
Running dist/bin/esbuild-local-server.js
 > ../node_modules/jsdom/lib/jsdom/utils.js:162:25: error: Could not resolve "canvas" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    162 │   const Canvas = require("canvas");
        ╵                          ~~~~~~~~

 > ../node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:31:57: warning: "./xhr-sync-worker.js" should be marked as external for use with "require.resolve"
    31 │ const syncWorkerFile = require.resolve ? require.resolve("./xhr-sync-worker.js") : null;
       ╵                                                          ~~~~~~~~~~~~~~~~~~~~~~

Error: Build failed with 1 error:
../node_modules/jsdom/lib/jsdom/utils.js:162:25: error: Could not resolve "canvas" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    at failureErrorWithLog (/Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:1432:15)
    at /Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:1114:28
    at runOnEndCallbacks (/Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:1033:48)
    at buildResponseToResult (/Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:1112:7)
    at /Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:1219:14
    at /Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:603:9
    at handleIncomingPacket (/Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:700:9)
    at Socket.readFromStdout (/Users/transverna/code/github/Howdju/howdju/premiser-api/node_modules/esbuild/lib/main.js:570:7)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "canvas" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)'
    }
  ],
  warnings: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: '"./xhr-sync-worker.js" should be marked as external for use with "require.resolve"'
    }
  ]
}
```

jsdom@21 says that canvas support is optional ([README](https://github.com/jsdom/jsdom/tree/4d1ef41615f38da1e6be89844521434dc588b435#canvas-support)). 

The problematic code is:

```
exports.Canvas = null;
let canvasInstalled = false;
try {
  require.resolve("canvas");
  canvasInstalled = true;
} catch (e) {
  // canvas is not installed
}
if (canvasInstalled) {
  const Canvas = require("canvas");
  if (typeof Canvas.createCanvas === "function") {
    // In browserify, the require will succeed but return an empty object
    exports.Canvas = Canvas;
  }
}
```

[source](https://github.com/jsdom/jsdom/blob/4d1ef41615f38da1e6be89844521434dc588b435/lib/jsdom/utils.js#L153-L167)

So it appears that jsdom uses `require.resolve` for `canvas detection`, but maybe something about our `esbuild` is breaking this detection.

**Comment by carlgieringer** [comment]
I tried to solve it by installing `@chialab/esbuild-plugin-require-resolve`, but I had to go back to version `0.12.39` to be compatible with node v14, and that version had this error `Could not resolve "pnpapi"`, which I couldn't work around (editing locally with the fixes in https://github.com/webpack/enhanced-resolve/issues/263 didn't work.)

**Comment by carlgieringer** [comment]
Finally I had to patch jsdom 21 to remove the dynamic require (https://github.com/Howdju/howdju/pull/433/commits/656fce4d57916aab8199d613cd6ef5ee7d42ab42). I'm not sure what functionality this might break. Because yarn's patch command applies the patch to all installed versions I had to remove the patch's resolution from the workspace root package.json or else the tests broke.
