### ISSUE TITLE
Some requests for media excerpt info fail

### ISSUE THREAD

**Issue by carlgieringer** [Howdju/howdju#445]
The error is below. Should we strip the text fragment before requesting?

- [x] https://www.science.org/content/article/exercise-actually-good-brain#:~:text=Other%20studies%20have%20focused%20on%20age%2Drelated%20cognitive%20decline.%20Research%20published%20in%20February%20in%20the%20Journal%20of%20Neurology%2C%20Neurosurgery%20%26%20Psychiatry%20tracked%20more%20than%201400%20people%20for%2030%20years%2C%20showing%20that%20more%20physical%20activity%20was%20associated%20with%20better%20cognitive%20performance%20at%20age%2069

```
{
    "timestamp": "2023-07-03T15:13:03.374Z",
    "context": {
        "clientRequestId": "d4f4fe86-bd8f-4ad7-886b-12251dd7a681",
        "serverRequestId": "527a1357-65d0-4ab7-93e7-c5a1203c8e1a",
        "stage": "pre_prod"
    },
    "level": "error",
    "levelNumber": 0,
    "message": "Unexpected error",
    "data": {
        "err": {
            "message": "Request failed with status code 403",
            "name": "AxiosError",
            "stack": "AxiosError: Request failed with status code 403\n    at settle (/node_modules/axios/lib/core/settle.js:19:12)\n    at BrotliDecompress.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:570:11)\n    at BrotliDecompress.emit (events.js:412:35)\n    at BrotliDecompress.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)",
            "config": {
                "transitional": {
                    "silentJSONParsing": true,
                    "forcedJSONParsing": true,
                    "clarifyTimeoutError": false
                },
                "adapter": [
                    "xhr",
                    "http"
                ],
                "transformRequest": [
                    null
                ],
                "transformResponse": [
                    null
                ],
                "timeout": 0,
                "xsrfCookieName": "XSRF-TOKEN",
                "xsrfHeaderName": "X-XSRF-TOKEN",
                "maxContentLength": -1,
                "maxBodyLength": -1,
                "env": {
                    "Blob": null
                },
                "headers": {
                    "Accept": "application/json, text/plain, */*",
                    "User-Agent": "axios/1.4.0",
                    "Accept-Encoding": "gzip, compress, deflate, br"
                },
                "method": "get",
                "url": "https://www.science.org/content/article/exercise-actually-good-brain#:~:text=Other%20studies%20have%20focused%20on%20age%2Drelated%20cognitive%20decline.%20Research%20published%20in%20February%20in%20the%20Journal%20of%20Neurology%2C%20Neurosurgery%20%26%20Psychiatry%20tracked%20more%20than%201400%20people%20for%2030%20years%2C%20showing%20that%20more%20physical%20activity%20was%20associated%20with%20better%20cognitive%20performance%20at%20age%2069."
            },
            "code": "ERR_BAD_REQUEST",
            "status": 403
        },
        "stack": "AxiosError: Request failed with status code 403\n    at settle (/node_modules/axios/lib/core/settle.js:19:12)\n    at BrotliDecompress.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:570:11)\n    at BrotliDecompress.emit (events.js:412:35)\n    at BrotliDecompress.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"
    }
}
```

**Comment by carlgieringer** [comment]
Works locally but fails remotely: https://www.seattletimes.com/seattle-news/homeless/heres-why-people-think-seattle-will-reverse-course-on-homelessness/#:~:text=Despite%20that%2C%20Francine,here%2C%E2%80%9D%20she%20said.
